id: 62b7a5cc83af4c2d9916e131b1af3f98
initial_creation_type: ocr
source_metadata:
  volumes:
    9a4165704ebe4a9c97455be603667115:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: ལས་ཀྱི་སྒྲིབ་པ་ཐམས་ཅད་རྣམ་པར་འཇོམས་པ་ཞེས་བྱ་བའི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1734
      volume_number: 34
